<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H96EUS9" name="com.saucedemo.testobjects.SauceDemoShoppingProjectTest" tests="8" failures="1" timestamp="6 Jan 2020 01:29:44 GMT" time="11.971" errors="0">
  <testcase name="validateProduct" time="1.635" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest"/>
  <testcase name="validatestandardUser" time="1.860" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest"/>
  <testcase name="validateCartTitle" time="2.157" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 5, Size: 4">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 5, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.saucedemo.pageobjects.InventoryPageObject.getProds(InventoryPageObject.java:131)
	at com.saucedemo.pageobjects.InventoryPageObject.getAllProductCountsAndCheckOut(InventoryPageObject.java:111)
	at com.saucedemo.testobjects.ShoppingCartTest.validateCartTitle(ShoppingCartTest.java:52)
	at com.saucedemo.testobjects.SauceDemoShoppingProjectTest.validateCartTitle(SauceDemoShoppingProjectTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- validateCartTitle -->
  <testcase name="validaeLogInPageTitle" time="0.036" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest"/>
  <testcase name="validateLockedUser" time="0.869" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest"/>
  <testcase name="validateAddToCartAndCheckout" time="0.829" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest"/>
  <testcase name="validateAddToCart" time="2.891" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest"/>
  <testcase name="validateProblemUser" time="1.694" classname="com.saucedemo.testobjects.SauceDemoShoppingProjectTest"/>
</testsuite> <!-- com.saucedemo.testobjects.SauceDemoShoppingProjectTest -->
